// const img = document.createElement('img');
// img.src = './jinn.jpeg';
// img.alt = 'Описание изображени12w12я';
// const container = document.querySelector('#images');
// container.append(img);
function getImg(){
const g = [
    "gesh/albedo.jpg",
    "gesh/alhaitam.jpg",
    "gesh/amber.jpg",
    "gesh/ayaka.jpg",
    "gesh/ayato.jpg",
    "gesh/baizhu.jpg",
    "gesh/barbara.jpg",
    "gesh/beidou.jpg",
    "gesh/bennet.jpg",
    "gesh/chugun.jpg",
    "gesh/dehya.jpg",
    "gesh/diluc.jpg",
    "gesh/diona.jpg",
    "gesh/dory.jpg",
    "gesh/ema.jpg",
    "gesh/faruzan.jpg",
    "gesh/fischil.jpg",
    "gesh/ganyu.jpg",
    "gesh/gorou.jpg",
    "gesh/heidzo.jpg",
    "gesh/itto.jpg",
    "gesh/jinn.jpg",
    "gesh/kandakia.jpg",
    "gesh/kaveh.jpg",
    "gesh/kaya.jpg",
    "gesh/kazuha.jpg",
    "gesh/keqing.jpg",
    "gesh/kirara.jpeg",
    "gesh/klee.jpg",
    "gesh/kokomi.jpg",
    "gesh/kollei.jpg",
    "gesh/kuki.jpg",
    "gesh/layla.webp",
    "gesh/linnet.jpg",
    "gesh/linni.jpg",
    "gesh/lisa.jpg",
    "gesh/mika.jpg",
    "gesh/mona.jpg",
    "gesh/nahida.jpeg",
    "gesh/nilu.jpg",
    "gesh/nina.jpg",
    "gesh/noell.jpg",
    "gesh/paymon.jpg",
    "gesh/qiqi.jpg",
    "gesh/raiden.jpg",
    "gesh/rayzor.jpg",
    "gesh/roza.jpg",
    "gesh/sara.jpg",
    "gesh/sayno.jpg",
    "gesh/sayu.jpg",
    "gesh/shenhe.jpg",
    "gesh/sinyan.jpg",
    "gesh/sinzu.jpg",
    "gesh/skara.jpg",
    "gesh/sukrose.jpg",
    "gesh/syanka.jpg",
    "gesh/tava.jpg",
    "gesh/tignary.jpg",
    "gesh/toma.jpg",
    "gesh/tort.jpg",
    "gesh/tr.jpg",
    "gesh/ula.jpg",
    "gesh/venty.jpg",
    "gesh/xiao.jpg",
    "gesh/yae.jpg",
    "gesh/yanfey.jpg",
    "gesh/yaoyao.jpg",
    "gesh/yelan.jpg",
    "gesh/zhonli.jpg",
    "gesh/zin.jpg",
];
let randomIndex = 
    Math.floor(Math.random() * g.length);
gensh.src = g[randomIndex];
}
